spring:
  application:
    name: spring-boot-aws-dynamodb

aws:
  dynamodb:
    access-key: ${AWS_DYNAMODB_ACCESS_KEY}
    secret-key: ${AWS_DYNAMODB_SECRET_KEY}
    region: us-east-1
    endpoint: dynamodb.us-east-1.amazonaws.com
